# Dependabot will run on day 14 of each month at 01:50 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "50 1 14 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "50 1 14 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "50 1 14 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"
